// <auto-generated />
using AirlineReservationSystem.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineReservationSystem.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230711130734_AddAirportTableAndSeed")]
    partial class AddAirportTableAndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AirlineReservationSystem.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Johannesburg",
                            Name = "OR Tambo International Airport",
                            Province = "Gauteng"
                        },
                        new
                        {
                            Id = 2,
                            City = "Cape Town",
                            Name = "Cape Town International Airport",
                            Province = "Western Cape"
                        },
                        new
                        {
                            Id = 3,
                            City = "Durban",
                            Name = "King Shaka International Airport",
                            Province = "KwaZulu-Natal"
                        },
                        new
                        {
                            Id = 4,
                            City = "Johannesburg",
                            Name = "Lanseria International Airport",
                            Province = "Gauteng"
                        },
                        new
                        {
                            Id = 5,
                            City = "Port Elizabeth",
                            Name = "Port Elizabeth International Airport",
                            Province = "Eastern Cape"
                        },
                        new
                        {
                            Id = 6,
                            City = "Nelspruit",
                            Name = "Kruger Mpumalanga International Airport",
                            Province = "Mpumalanga"
                        },
                        new
                        {
                            Id = 7,
                            City = "East London",
                            Name = "East London Airport",
                            Province = "Eastern Cape"
                        },
                        new
                        {
                            Id = 8,
                            City = "Bloemfontein",
                            Name = "Bram Fischer International Airport",
                            Province = "Free State"
                        },
                        new
                        {
                            Id = 9,
                            City = "George",
                            Name = "George Airport",
                            Province = "Western Cape"
                        },
                        new
                        {
                            Id = 10,
                            City = "Kimberley",
                            Name = "Kimberley Airport",
                            Province = "Northern Cape"
                        },
                        new
                        {
                            Id = 11,
                            City = "Upington",
                            Name = "Upington International Airport",
                            Province = "Northern Cape"
                        },
                        new
                        {
                            Id = 12,
                            City = "Pilanesberg",
                            Name = "Pilanesberg International Airport",
                            Province = "North West"
                        },
                        new
                        {
                            Id = 13,
                            City = "Margate",
                            Name = "Margate Airport",
                            Province = "KwaZulu-Natal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
